name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: sudo apt-get update && sudo apt-get install libpugixml-dev libcurl4-gnutls-dev libboost-all-dev
    - name: Create Build directory
      run: mkdir ${{github.workspace}}/build
      
    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake -S ${{github.workspace}} -B .
      

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build/tests
      run: ctest 
      
